language: r

os: 
 - linux
 - windows

repos:
  CRAN: https://cloud.r-project.org
  molgenis: https://registry.molgenis.org/repository/R/

cache:
  packages: yes

r:
  - release
  - oldrel

script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran