language: r

repos:
  CRAN: https://cloud.r-project.org
  molgenis: https://registry.molgenis.org/repository/R/

cache:
  packages: yes

matrix:
  include:
  - os: linux
    r: release
    script:
      - R CMD build . --compact-vignettes=gs+qpdf
      - R CMD check *tar.gz --as-cran
  - os: windows
    language: shell
    before_install:
      - source .ci/.travis.win.install.sh
    script:
      - R.exe CMD build . --compact-vignettes=gs+qpdf
      - R.exe CMD check *tar.gz --as-cran
      - R.exe CMD build . --binary
