# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

addons:
 apt:
   packages:
   - libharfbuzz-dev 
   - libfribidi-dev
   - libnlopt-dev

cache: 
  apt: true
  packages: true

before_cache: 
  - Rscript -e 'remotes::install_cran("pkgdown")'
  - Rscript -e 'remotes::install_github("datashield/dsBaseClient", ref=v6.0.1)'
  - Rscript -e 'remotes::install_github("lifecycle-project/ds-helper", ref=master)'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
  skip_cleanup: true
  on:
    branch: master
